workflows:
  ios-release:
    name: iOS Release Build
    environment:
      groups:
        - codemagic_credentials   # groupe avec ton GITHUB_TOKEN + secrets de signature
      vars:
        APPLE_ID: "michel.estorge@outlook.fr"
        APP_SPECIFIC_PASSWORD: "ReseauPME2025!"
        TEAM_ID: "S65D65K22C"
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.picmedia.reseaupme

    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Bump iOS deployment target
        script: |
          sed -i '' "s/platform :ios, '.*'/platform :ios, '14.0'/" ios/Podfile
          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g" ios/Runner.xcodeproj/project.pbxproj

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Apply provisioning profiles & certificates
        script: |
          xcode-project use-profiles

      - name: Archive with xcodebuild
        script: |
          xcodebuild clean -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos

          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            DEVELOPMENT_TEAM=$TEAM_ID \
            CODE_SIGN_STYLE=Manual

      - name: Export signed IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportMethod app-store \
            -exportPath build/ios/ipa \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa

