workflows:
  ios-release:
    name: iOS Release Build
    environment:
      groups:
        - github_access  # ton groupe avec GITHUB_TOKEN
      vars:
        APPLE_ID: "michel.estorge@outlook.fr"
        APP_SPECIFIC_PASSWORD: "ReseauPME2025!"
        CERTIFICATE_PASSWORD: "ReseauPME2025!"
        TEAM_ID: "S65D65K22C"
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.picmedia.reseaupme

    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build ipa
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
