workflows:
  ios-release:
    name: iOS Release Build
    environment:
      groups:
        - codemagic_credentials
      vars:
        APPLE_ID: "michel.estorge@outlook.fr"
        APP_SPECIFIC_PASSWORD: "ReseauPME2025!"
        TEAM_ID: "S65D65K22C"
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.picmedia.reseaupme

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Set iOS deployment target to 14.0
        script: |
          sed -i '' "s/platform :ios, '.*'/platform :ios, '14.0'/" ios/Podfile

      - name: Clean and reinstall CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -rf ~/Library/Developer/Xcode/DerivedData
          pod install --repo-update
          cd ..


      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist ios/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
