workflows:
  ios-release:
    name: Build iOS App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build ipa
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa

