workflows:
  ios-release:
    name: iOS Release Build
    environment:
      groups:
        - codemagic_credentials
      vars:
        APPLE_ID: "michel.estorge@outlook.fr"
        APP_SPECIFIC_PASSWORD: "ReseauPME2025!"
        TEAM_ID: "S65D65K22C"
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.picmedia.reseaupme

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Bump iOS deployment target
        script: |
          sed -i '' "s/platform :ios, '.*'/platform :ios, '14.0'/" ios/Podfile

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA with Codemagic CLI
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-method app-store \
            --export-path build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa

