name: reseaupme
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.8.0
  flutter_google_places_hoc081098: ^1.2.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter: ^2.12.3
  geolocator: ^10.0.0
  intl: ^0.18.1
  google_api_headers:
    path: lib_plugins/google_api_headers/
  package_info_plus: ^4.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2 # ← vérifie sur pub.dev pour la dernière version


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5
  flutter_launcher_icons: ^0.14.3
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/splash/logo.png
    - assets/icon/icon.png


dependency_overrides:
  google_api_headers:
    path: lib_plugins/google_api_headers/
